---
- name: PC5 - Resolución
  hosts: all
  become: true
  become_method: sudo
  remote_user: vagrant
  vars:
  gather_facts: no
  pre_tasks:
    - raw: apt-get install -y python-simplejson
  tasks:
    - import_tasks: actividades/actividad1.yml
    - import_tasks: actividades/actividad2.yml


  handlers:
    - name: Reiniciar servidor SSH
      service:
        name: ssh
        state: restarteds
    - name: restart nginx
      service: name=nginx state=reloaded